sudo: required
language: node_js
node_js: stable

# Ubuntu Trusty
dist: trusty

addons:
apt:
sources:
- google-chrome
packages:
- google-chrome-stable
- google-chrome-beta

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
# Update docker-engine using Ubuntu 'trusty' apt repo
- curl -sSL "https://get.docker.com/gpg" | sudo -E apt-key add -
- echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update
- sudo apt-get install docker-engine
- docker version
# Update docker-compose via pip
- sudo pip install docker-compose
- docker-compose version

before_script:
# Setup docker
- docker-compose up --build -d
# For logging purposes
- docker ps
# Install deps
- npm install
# Build
- npm run build

script:
# Execute tests
- npm test

after_script:
# Close docker
- docker-compose down
